#!/bin/bash

if [ ! "$#" -eq "5" ]
  then
    echo 'webpipe2lucene shell takes a list of documents (defined by an schema'
    echo 'file) from a piped file and insert then into a DeDup index.'
    echo
    echo 'usage: webpipe2lucene'
    echo '   <pipeFile> - pipe file generated by webpipe2lucene shell'
    echo '   <pipeEncoding> - pipe file encoding'
    echo '   <DeDupServiceBase> - url of DeDup service'
    echo '   <indexName> - DeDup index where the new documents will br inserted'
    echo '   <schemaName> - DeDup schema file (describing document structure)'
    exit 1
fi

sbt "run-main org.bireme.dcdup.WebPipe2Lucene $1 $2 $3 $4 $5"
